-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 13:14:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cybercafe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cybercafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cybercafe` DEFAULT CHARACTER SET utf8 ;
USE `cybercafe` ;

-- -----------------------------------------------------
-- Table `cybercafe`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `numero_endereco` VARCHAR(5) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `bairro` VARCHAR(70) NOT NULL,
  `cidade` VARCHAR(70) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `logradouro` VARCHAR(70) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `email_funcionario` VARCHAR(75) NOT NULL,
  `data_contratacao` DATE NOT NULL,
  `data_nasc_funcionario` DATE NOT NULL,
  `Tel_cel_func` VARCHAR(17) NULL,
  `Tel_fixo_func` VARCHAR(13) NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  CONSTRAINT `fk_endfunc`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `cybercafe`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `nome_fornecedor` VARCHAR(70) NOT NULL,
  `email_fornecedor` VARCHAR(70) NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL UNIQUE,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`EnderecoFornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`EnderecoFornecedor` (
  `id_endereco` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  CONSTRAINT `fk_fe_end`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `cybercafe`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fe_forn`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `cybercafe`.`Fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `emissao_compra` DATE NOT NULL,
  `previsao_compra` DATE NOT NULL,
  `atendida_compra` TINYINT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`CompraFornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`CompraFornecedor` (
  `id_compra` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  CONSTRAINT `fk_cf_com`
    FOREIGN KEY (`id_compra`)
    REFERENCES `cybercafe`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cf_forn`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `cybercafe`.`Fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `nome_produto` VARCHAR(45) NOT NULL,
  `quantidade_produto` INT NOT NULL,
  `preco_produto` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`ItemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`ItemCompra` (
  `id_compra` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `preco_itemcompra` DOUBLE NOT NULL,
  `quantidade_comprada` DOUBLE NOT NULL,
  PRIMARY KEY (`id_compra`, `id_produto`),
  CONSTRAINT `fk_ic_com`
    FOREIGN KEY (`id_compra`)
    REFERENCES `cybercafe`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ic_prod`
    FOREIGN KEY (`id_produto`)
    REFERENCES `cybercafe`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(75) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `data_nasc_usuario` DATE NOT NULL,
  `tel_cel_usuario` VARCHAR(17) NOT NULL,
  `tel_fixo_usuario` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`EnderecoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`EnderecoUsuario` (
  `id_endereco` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  CONSTRAINT `fk_eu_end`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `cybercafe`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eu_usu`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cybercafe`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`NotaFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`NotaFiscal` (
  `numero_notaFiscal` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `emissao_notaFiscal` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`numero_notaFiscal`),
  CONSTRAINT `fk_nf_usu`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cybercafe`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`ItemNotaFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`ItemNotaFiscal` (
  `id_notaFiscal` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade_ItemNotaFiscal` INT NOT NULL,
  `preco_ItemNotaFiscal` DOUBLE NOT NULL,
  PRIMARY KEY (`id_notaFiscal`, `id_produto`),
  CONSTRAINT `fk_inf_nf`
    FOREIGN KEY (`id_notaFiscal`)
    REFERENCES `cybercafe`.`NotaFiscal` (`numero_notaFiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inf_prod`
    FOREIGN KEY (`id_produto`)
    REFERENCES `cybercafe`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cybercafe`.`UsoPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cybercafe`.`UsoPC` (
  `id_usoPC` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `numero_pc` INT NOT NULL,
  `numero_notaFiscal` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_hora_inicio` DATE NOT NULL,
  `data_hora_fim` DATE NOT NULL,
  `preco_uso` DOUBLE NOT NULL,
  PRIMARY KEY (`id_usoPC`),
  CONSTRAINT `fk_uso_u`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cybercafe`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uso_nf`
    FOREIGN KEY (`numero_notaFiscal`)
    REFERENCES `cybercafe`.`NotaFiscal` (`numero_notaFiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;